Placeholders translated on register form
CodenityOrg/helpet-FE pull request #70
Opened 2020-04-30 02:39 UTC by osgigon

2020-04-30 23:23 UTC, florenperetti commented on src/localization/en.js
> +    beforeContent:'Accept the',
change to "I accept the "

2020-04-30 23:24 UTC, florenperetti requested changes
@osgigon some little fixes here

2020-04-30 23:24 UTC, florenperetti commented on src/localization/en.js
> +    beforeContent:'Accept the',
Change to "I accept the "

2020-04-30 23:24 UTC, florenperetti commented on src/views/RegisterView.vue
> +                                    name="mail"
Fix: should be name="password"

2020-05-01 00:57 UTC, florenperetti approved these changes

2020-05-01 00:58 UTC, florenperetti approved these changes

2020-05-04 13:54 UTC, florenperetti approved these changes

2020-05-04 16:10 UTC, CristianPeralta approved these changes

2020-05-04 20:22 UTC, merged